app = "filippo-whoami"

[[services]]
  internal_port = 2222
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 100
    soft_limit = 75
    type = "connections"

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    restart_limit = 6
    timeout = "2s"

[env]
  LISTEN_DEBUG = ":6000"
  LISTEN_SSH = ":2222"
