app = "filippo-whoami"

[deploy]
  strategy = "bluegreen"

[metrics]
  port = 9091
  path = "/metrics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 2222
  protocol = "tcp"
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    restart_limit = 6
    timeout = "2s"
