app = "filippo-whoami"

[metrics]
  port = 9091
  path = "/metrics"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[services]]
  internal_port = 2222
  protocol = "tcp"

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    restart_limit = 6
    timeout = "2s"
